language: ruby
sudo: false
cache:
  directories:
  - /tmp/solr-5.3.0

notifications:
  email: false

rvm:
  - 2.3.0
  - 2.2.4

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
